### ISSUE TITLE
Question: How can this package be used to download img from a URL?

### ISSUE THREAD

**Issue by mizukageyama** [xclud/dart_download#1]
How can this package be used to download img from a URL? Is there any example for this?

**Comment by xclud** [comment]
I am working to add a `downloadFromUri` function. Meanwhile you may get a Stream<int> from the package of your choice (e.g. `http` or `dio`) and pass it to the download function.

I will let you know when i complete the new function.

**Comment by abc3685029** [comment]
> I am working to add a `downloadFromUri` function. Meanwhile you may get a Stream from the package of your choice (e.g. `http` or `dio`) and pass it to the download function.
> 
> I will let you know when i complete the new function.

Hello,when will it be finished?Thanks!

**Comment by xclud** [comment]
There is no ETA. But i do my best to update the package ASAP.

**Comment by newradius** [comment]
How do you create a stream compatible with the library from dio?

**Comment by xclud** [comment]
@newradius 
Any `Stream` object will do.

**Comment by newradius** [comment]
> @newradius Any `Stream` object will do.

I tried with:

```
Future downloadFile(String imageUrl) async {
  Response<ResponseBody> rs;
  rs = await Dio().get<ResponseBody>(
    'https://i.picsum.photos/id/492/1920/1080.jpg?hmac=_kiWj9u8dWK4CKGUbl3Yp2GM1bQzyse4KKBhvedwfz4',
    options: Options(
        responseType: ResponseType.stream), // set responseType to stream
  );

  download(rs.data.stream, 'image.png');
}
```

But the stream is not compatible: The argument type 'Stream<Uint8List>' can't be assigned to the parameter type 'Stream<int>

**Comment by xclud** [comment]
Can you send a full project? Either a link to github repo or attaching a zip file.

**Comment by newradius** [comment]
Sure, you can download it here https://we.tl/t-8LsRqMRw1I the piece of code is located at lib/image_container/image_container_widget.dart 

The project was made with flutterflow.

**Comment by xclud** [comment]
ok, here's the fix you need:

```
  final stream = rs.data!.stream.transform(
    StreamTransformer<Uint8List, int>.fromHandlers(
      handleData: (value, sink) {
        for (final v in value) {
          sink.add(v);
        }
      },
    ),
  );

  download(stream, 'image.png');
```

**Comment by newradius** [comment]
It worked, thank you!

**Comment by xclud** [comment]
I am closing this issue coz it has gone off topic. Please feel free to open a new issue.
