### ISSUE TITLE
download not working on windows 10

### ISSUE THREAD

**Issue by rehanazher** [xclud/dart_download#2]
I am having issues when using it on Windows Platform , it does not do anything . 

My code is as simple as below:

```
 final stream =Stream.fromIterable(csvString.codeUnits);
 download(stream, "weather.csv");
```
Any special thing that we need to do for windows and I have missed those.
Thanks

**Comment by xclud** [comment]
@rehanazher You should have a file named `weather.csv` next to your exe.

**Comment by rehanazher** [comment]
Ah Yes it is there, any way possible that we can make the app show file save dialog. 

Thanks

**Comment by xclud** [comment]
I guess this is what you are looking for: https://pub.dev/packages/file_picker

**Comment by xclud** [comment]
I suppose this is issue is resolve. I am closing but feel free to open a new issue any time.
