### ISSUE TITLE
does it work on mobile platform? (Android)

### ISSUE THREAD

**Issue by kkangz** [xclud/dart_download#3]
I tried to use this plugin with sample code but "hello.txt" is not downloaded on device even I checked storage permission .

```
final stream = Stream.fromIterable('Hello World!'.codeUnits);
download(stream, 'hello.txt');

```
also checked with the path "/sdcard/hello.txt" too.
should I check permissions more? 

E/flutter (31084): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/sdcard/hello.txt' (OS Error: Permission denied, errno = 13)
E/flutter (31084): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter (31084): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (31084): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (31084): <asynchronous suspension>
E/flutter (31084):

**Comment by xclud** [comment]
This is most-likely because of permission. You can also get the current directory or documents directory using [path_provider](https://pub.dev/packages/path_provider).

Please let me know if this fixes your problem.

**Comment by rayhanhanaputra** [comment]
how to make the download visible on the notification bar?

**Comment by xclud** [comment]
@rayhanhanaputra Currently, this package does not support foreground downloads.
