### ISSUE TITLE
Download and save video files in WEB

### ISSUE THREAD

**Issue by aytunch** [xclud/dart_download#4]
Thanks for this package.

We are working on a video intensive web app and we want to preload the next couple of videos in the feed. 
We want to download 3-4 videos first and then play them from `.file("xxx")` source instead of `network`. However let alone caching, even downloading in the web platform seems not possible if I am not wrong. With this package can we save videos from a network url?

**Comment by xclud** [comment]
Hi,

This is a dup of #1.

**Comment by xclud** [comment]
I close this issue but please feel free to open a new issue.
