### ISSUE TITLE
Not Working In Android

### ISSUE THREAD

**Issue by oren777** [xclud/dart_download#6]
Hi, i tried everything, with path, without path, with permission for everything, with permission_handler, everything! its working just on website.

**Comment by vatankh** [comment]
same here not working on android

**Comment by xclud** [comment]
This package is web-only.

I close this issue but please feel free to open a new issue.

**Comment by newradius** [comment]
You listed it as all platforms in pub.dev

**Comment by xclud** [comment]
Sorry I wrote my other post by a mistake. Please let me check the problem.

**Comment by bulgariamitko** [comment]
I have the same problem. It is not working on Android.

**Comment by oren777** [comment]
I don't remember how but i fixed the problem with his package and its working for me now
